/*
 * generated by Xtext 2.20.0
 */
package org.xtext.metadoodle;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MDLStandaloneSetup extends MDLStandaloneSetupGenerated {

	public static void doSetup() {
		new MDLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
