/**
 * generated by Xtext 2.19.0
 */
package org.xtext.mdl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.mdl.MdlRuntimeModule;
import org.xtext.mdl.MdlStandaloneSetup;
import org.xtext.mdl.ide.MdlIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MdlIdeSetup extends MdlStandaloneSetup {
  @Override
  public Injector createInjector() {
    MdlRuntimeModule _mdlRuntimeModule = new MdlRuntimeModule();
    MdlIdeModule _mdlIdeModule = new MdlIdeModule();
    return Guice.createInjector(Modules2.mixin(_mdlRuntimeModule, _mdlIdeModule));
  }
}
