/**
 * generated by Xtext 2.19.0
 */
package org.xtext.mdl.ide;

import org.xtext.mdl.ide.AbstractMdlIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MdlIdeModule extends AbstractMdlIdeModule {
}
