/**
 * generated by Xtext 2.19.0
 */
package org.xtext.mdl.ide;

import org.xtext.mdl.ide.AbstractV1IdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class V1IdeModule extends AbstractV1IdeModule {
}
