/**
 * generated by Xtext 2.19.0
 */
package org.xtext.mdl.v1.util;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

import org.xtext.mdl.v1.Contenu;
import org.xtext.mdl.v1.Depot;
import org.xtext.mdl.v1.EndCond;
import org.xtext.mdl.v1.Mail;
import org.xtext.mdl.v1.QCM;
import org.xtext.mdl.v1.Reminder;
import org.xtext.mdl.v1.Step;
import org.xtext.mdl.v1.SynchDate;
import org.xtext.mdl.v1.TypeQCM;
import org.xtext.mdl.v1.V1Package;
import org.xtext.mdl.v1.Workflow;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see org.xtext.mdl.v1.V1Package
 * @generated
 */
public class V1Switch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static V1Package modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public V1Switch()
  {
    if (modelPackage == null)
    {
      modelPackage = V1Package.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case V1Package.WORKFLOW:
      {
        Workflow workflow = (Workflow)theEObject;
        T result = caseWorkflow(workflow);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case V1Package.STEP:
      {
        Step step = (Step)theEObject;
        T result = caseStep(step);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case V1Package.OBJECT:
      {
        org.xtext.mdl.v1.Object object = (org.xtext.mdl.v1.Object)theEObject;
        T result = caseObject(object);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case V1Package.END_COND:
      {
        EndCond endCond = (EndCond)theEObject;
        T result = caseEndCond(endCond);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case V1Package.SYNCH_DATE:
      {
        SynchDate synchDate = (SynchDate)theEObject;
        T result = caseSynchDate(synchDate);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case V1Package.DEPOT:
      {
        Depot depot = (Depot)theEObject;
        T result = caseDepot(depot);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case V1Package.QCM:
      {
        QCM qcm = (QCM)theEObject;
        T result = caseQCM(qcm);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case V1Package.TYPE_QCM:
      {
        TypeQCM typeQCM = (TypeQCM)theEObject;
        T result = caseTypeQCM(typeQCM);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case V1Package.REMINDER:
      {
        Reminder reminder = (Reminder)theEObject;
        T result = caseReminder(reminder);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case V1Package.MAIL:
      {
        Mail mail = (Mail)theEObject;
        T result = caseMail(mail);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case V1Package.CONTENU:
      {
        Contenu contenu = (Contenu)theEObject;
        T result = caseContenu(contenu);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Workflow</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Workflow</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseWorkflow(Workflow object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Step</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Step</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseStep(Step object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Object</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Object</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseObject(org.xtext.mdl.v1.Object object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>End Cond</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>End Cond</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEndCond(EndCond object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Synch Date</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Synch Date</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSynchDate(SynchDate object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Depot</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Depot</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDepot(Depot object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>QCM</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>QCM</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseQCM(QCM object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Type QCM</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Type QCM</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTypeQCM(TypeQCM object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Reminder</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Reminder</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseReminder(Reminder object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Mail</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Mail</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMail(Mail object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Contenu</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Contenu</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseContenu(Contenu object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //V1Switch
