/**
 * generated by Xtext 2.19.0
 */
package org.xtext.mdl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.mdl.ui.AbstractMdlUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MdlUiModule extends AbstractMdlUiModule {
  public MdlUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
