/**
 * generated by Xtext 2.19.0
 */
package org.xtext.mdl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.mdl.ui.AbstractV1UiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class V1UiModule extends AbstractV1UiModule {
  public V1UiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
