/**
 * generated by Xtext 2.19.0
 */
package org.xtext.mdl.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class V1QuickfixProvider extends DefaultQuickfixProvider {
}
