/**
 * generated by Xtext 2.19.0
 */
package org.xtext.mdl.v1;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Depot</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mdl.v1.Depot#getIntitule <em>Intitule</em>}</li>
 *   <li>{@link org.xtext.mdl.v1.Depot#getLimiteSize <em>Limite Size</em>}</li>
 *   <li>{@link org.xtext.mdl.v1.Depot#getFormat <em>Format</em>}</li>
 * </ul>
 *
 * @see org.xtext.mdl.v1.V1Package#getDepot()
 * @model
 * @generated
 */
public interface Depot extends EObject
{
  /**
   * Returns the value of the '<em><b>Intitule</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Intitule</em>' attribute.
   * @see #setIntitule(String)
   * @see org.xtext.mdl.v1.V1Package#getDepot_Intitule()
   * @model
   * @generated
   */
  String getIntitule();

  /**
   * Sets the value of the '{@link org.xtext.mdl.v1.Depot#getIntitule <em>Intitule</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Intitule</em>' attribute.
   * @see #getIntitule()
   * @generated
   */
  void setIntitule(String value);

  /**
   * Returns the value of the '<em><b>Limite Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Limite Size</em>' attribute.
   * @see #setLimiteSize(int)
   * @see org.xtext.mdl.v1.V1Package#getDepot_LimiteSize()
   * @model
   * @generated
   */
  int getLimiteSize();

  /**
   * Sets the value of the '{@link org.xtext.mdl.v1.Depot#getLimiteSize <em>Limite Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Limite Size</em>' attribute.
   * @see #getLimiteSize()
   * @generated
   */
  void setLimiteSize(int value);

  /**
   * Returns the value of the '<em><b>Format</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Format</em>' attribute list.
   * @see org.xtext.mdl.v1.V1Package#getDepot_Format()
   * @model unique="false"
   * @generated
   */
  EList<String> getFormat();

} // Depot
