/**
 * generated by Xtext 2.19.0
 */
package org.xtext.mdl.v1;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Synch Date</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mdl.v1.SynchDate#getStart <em>Start</em>}</li>
 *   <li>{@link org.xtext.mdl.v1.SynchDate#getEnd <em>End</em>}</li>
 *   <li>{@link org.xtext.mdl.v1.SynchDate#getPrecision <em>Precision</em>}</li>
 * </ul>
 *
 * @see org.xtext.mdl.v1.V1Package#getSynchDate()
 * @model
 * @generated
 */
public interface SynchDate extends EObject
{
  /**
   * Returns the value of the '<em><b>Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start</em>' attribute.
   * @see #setStart(String)
   * @see org.xtext.mdl.v1.V1Package#getSynchDate_Start()
   * @model
   * @generated
   */
  String getStart();

  /**
   * Sets the value of the '{@link org.xtext.mdl.v1.SynchDate#getStart <em>Start</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start</em>' attribute.
   * @see #getStart()
   * @generated
   */
  void setStart(String value);

  /**
   * Returns the value of the '<em><b>End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End</em>' attribute.
   * @see #setEnd(String)
   * @see org.xtext.mdl.v1.V1Package#getSynchDate_End()
   * @model
   * @generated
   */
  String getEnd();

  /**
   * Sets the value of the '{@link org.xtext.mdl.v1.SynchDate#getEnd <em>End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End</em>' attribute.
   * @see #getEnd()
   * @generated
   */
  void setEnd(String value);

  /**
   * Returns the value of the '<em><b>Precision</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Precision</em>' attribute.
   * @see #setPrecision(String)
   * @see org.xtext.mdl.v1.V1Package#getSynchDate_Precision()
   * @model
   * @generated
   */
  String getPrecision();

  /**
   * Sets the value of the '{@link org.xtext.mdl.v1.SynchDate#getPrecision <em>Precision</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Precision</em>' attribute.
   * @see #getPrecision()
   * @generated
   */
  void setPrecision(String value);

} // SynchDate
