/**
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.v1.validation;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class V1Validator /* implements AbstractV1Validator  */{
}
