/**
 * generated by Xtext 2.19.0
 */
package org.xtext.mdl.mdl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cond Fin</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mdl.mdl.CondFin#getDate <em>Date</em>}</li>
 *   <li>{@link org.xtext.mdl.mdl.CondFin#getParticipantsRequired <em>Participants Required</em>}</li>
 * </ul>
 *
 * @see org.xtext.mdl.mdl.MdlPackage#getCondFin()
 * @model
 * @generated
 */
public interface CondFin extends EObject
{
  /**
   * Returns the value of the '<em><b>Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Date</em>' attribute.
   * @see #setDate(String)
   * @see org.xtext.mdl.mdl.MdlPackage#getCondFin_Date()
   * @model
   * @generated
   */
  String getDate();

  /**
   * Sets the value of the '{@link org.xtext.mdl.mdl.CondFin#getDate <em>Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Date</em>' attribute.
   * @see #getDate()
   * @generated
   */
  void setDate(String value);

  /**
   * Returns the value of the '<em><b>Participants Required</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Participants Required</em>' attribute.
   * @see #setParticipantsRequired(int)
   * @see org.xtext.mdl.mdl.MdlPackage#getCondFin_ParticipantsRequired()
   * @model
   * @generated
   */
  int getParticipantsRequired();

  /**
   * Sets the value of the '{@link org.xtext.mdl.mdl.CondFin#getParticipantsRequired <em>Participants Required</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Participants Required</em>' attribute.
   * @see #getParticipantsRequired()
   * @generated
   */
  void setParticipantsRequired(int value);

} // CondFin
