/**
 * generated by Xtext 2.19.0
 */
package org.xtext.mdl.mdl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mail</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mdl.mdl.Mail#getExpediteur <em>Expediteur</em>}</li>
 *   <li>{@link org.xtext.mdl.mdl.Mail#getDestinataire <em>Destinataire</em>}</li>
 *   <li>{@link org.xtext.mdl.mdl.Mail#getPj <em>Pj</em>}</li>
 *   <li>{@link org.xtext.mdl.mdl.Mail#getCorps <em>Corps</em>}</li>
 * </ul>
 *
 * @see org.xtext.mdl.mdl.MdlPackage#getMail()
 * @model
 * @generated
 */
public interface Mail extends EObject
{
  /**
   * Returns the value of the '<em><b>Expediteur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expediteur</em>' attribute.
   * @see #setExpediteur(String)
   * @see org.xtext.mdl.mdl.MdlPackage#getMail_Expediteur()
   * @model
   * @generated
   */
  String getExpediteur();

  /**
   * Sets the value of the '{@link org.xtext.mdl.mdl.Mail#getExpediteur <em>Expediteur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expediteur</em>' attribute.
   * @see #getExpediteur()
   * @generated
   */
  void setExpediteur(String value);

  /**
   * Returns the value of the '<em><b>Destinataire</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Destinataire</em>' attribute list.
   * @see org.xtext.mdl.mdl.MdlPackage#getMail_Destinataire()
   * @model unique="false"
   * @generated
   */
  EList<String> getDestinataire();

  /**
   * Returns the value of the '<em><b>Pj</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pj</em>' attribute.
   * @see #setPj(String)
   * @see org.xtext.mdl.mdl.MdlPackage#getMail_Pj()
   * @model
   * @generated
   */
  String getPj();

  /**
   * Sets the value of the '{@link org.xtext.mdl.mdl.Mail#getPj <em>Pj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pj</em>' attribute.
   * @see #getPj()
   * @generated
   */
  void setPj(String value);

  /**
   * Returns the value of the '<em><b>Corps</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Corps</em>' containment reference.
   * @see #setCorps(Contenu)
   * @see org.xtext.mdl.mdl.MdlPackage#getMail_Corps()
   * @model containment="true"
   * @generated
   */
  Contenu getCorps();

  /**
   * Sets the value of the '{@link org.xtext.mdl.mdl.Mail#getCorps <em>Corps</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Corps</em>' containment reference.
   * @see #getCorps()
   * @generated
   */
  void setCorps(Contenu value);

} // Mail
