/**
 * generated by Xtext 2.19.0
 */
package org.xtext.mdl.mdl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.mdl.mdl.MdlPackage
 * @generated
 */
public interface MdlFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MdlFactory eINSTANCE = org.xtext.mdl.mdl.impl.MdlFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Workflow</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Workflow</em>'.
   * @generated
   */
  Workflow createWorkflow();

  /**
   * Returns a new object of class '<em>Step</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Step</em>'.
   * @generated
   */
  Step createStep();

  /**
   * Returns a new object of class '<em>Object</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Object</em>'.
   * @generated
   */
  Object createObject();

  /**
   * Returns a new object of class '<em>Cond Fin</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Cond Fin</em>'.
   * @generated
   */
  CondFin createCondFin();

  /**
   * Returns a new object of class '<em>Synch Date</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Synch Date</em>'.
   * @generated
   */
  SynchDate createSynchDate();

  /**
   * Returns a new object of class '<em>Depot</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Depot</em>'.
   * @generated
   */
  Depot createDepot();

  /**
   * Returns a new object of class '<em>QCM</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>QCM</em>'.
   * @generated
   */
  QCM createQCM();

  /**
   * Returns a new object of class '<em>Type QCM</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type QCM</em>'.
   * @generated
   */
  TypeQCM createTypeQCM();

  /**
   * Returns a new object of class '<em>Reminder</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Reminder</em>'.
   * @generated
   */
  Reminder createReminder();

  /**
   * Returns a new object of class '<em>Mail</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mail</em>'.
   * @generated
   */
  Mail createMail();

  /**
   * Returns a new object of class '<em>Contenu</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Contenu</em>'.
   * @generated
   */
  Contenu createContenu();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MdlPackage getMdlPackage();

} //MdlFactory
