/**
 * generated by Xtext 2.19.0
 */
package org.xtext.mdl.mdl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reminder</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mdl.mdl.Reminder#getDate <em>Date</em>}</li>
 *   <li>{@link org.xtext.mdl.mdl.Reminder#getMail <em>Mail</em>}</li>
 * </ul>
 *
 * @see org.xtext.mdl.mdl.MdlPackage#getReminder()
 * @model
 * @generated
 */
public interface Reminder extends EObject
{
  /**
   * Returns the value of the '<em><b>Date</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Date</em>' attribute list.
   * @see org.xtext.mdl.mdl.MdlPackage#getReminder_Date()
   * @model unique="false"
   * @generated
   */
  EList<String> getDate();

  /**
   * Returns the value of the '<em><b>Mail</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mail</em>' containment reference.
   * @see #setMail(Mail)
   * @see org.xtext.mdl.mdl.MdlPackage#getReminder_Mail()
   * @model containment="true"
   * @generated
   */
  Mail getMail();

  /**
   * Sets the value of the '{@link org.xtext.mdl.mdl.Reminder#getMail <em>Mail</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mail</em>' containment reference.
   * @see #getMail()
   * @generated
   */
  void setMail(Mail value);

} // Reminder
