/**
 * generated by Xtext 2.19.0
 */
package org.xtext.mdl.mdl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Workflow</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mdl.mdl.Workflow#getDateDebut <em>Date Debut</em>}</li>
 *   <li>{@link org.xtext.mdl.mdl.Workflow#getSteps <em>Steps</em>}</li>
 * </ul>
 *
 * @see org.xtext.mdl.mdl.MdlPackage#getWorkflow()
 * @model
 * @generated
 */
public interface Workflow extends EObject
{
  /**
   * Returns the value of the '<em><b>Date Debut</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Date Debut</em>' attribute.
   * @see #setDateDebut(String)
   * @see org.xtext.mdl.mdl.MdlPackage#getWorkflow_DateDebut()
   * @model
   * @generated
   */
  String getDateDebut();

  /**
   * Sets the value of the '{@link org.xtext.mdl.mdl.Workflow#getDateDebut <em>Date Debut</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Date Debut</em>' attribute.
   * @see #getDateDebut()
   * @generated
   */
  void setDateDebut(String value);

  /**
   * Returns the value of the '<em><b>Steps</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.mdl.mdl.Step}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Steps</em>' containment reference list.
   * @see org.xtext.mdl.mdl.MdlPackage#getWorkflow_Steps()
   * @model containment="true"
   * @generated
   */
  EList<Step> getSteps();

} // Workflow
