/*
 * generated by Xtext 2.19.0
 */
package org.xtext.mdl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MdlStandaloneSetup extends MdlStandaloneSetupGenerated {

	def static void doSetup() {
		new MdlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
