/*
 * generated by Xtext 2.19.0
 */
package org.xtext.mdl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMdlScopeProvider extends DelegatingScopeProvider {
}
