/*
 * generated by Xtext 2.19.0
 */
package org.xtext.mdl.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.mdl.MdlRuntimeModule
import org.xtext.mdl.MdlStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MdlIdeSetup extends MdlStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MdlRuntimeModule, new MdlIdeModule))
	}
	
}
