/*
 * generated by Xtext 2.19.0
 */
package org.xtext.mdl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.mdl.ui.internal.MdlActivator;

public class V1UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MdlActivator.getInstance().getInjector("org.xtext.mdl.V1");
	}

}
