/**
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.v1;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class V1StandaloneSetup /* implements V1StandaloneSetupGenerated  */{
  public static void doSetup() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method createInjectorAndDoEMFRegistration() is undefined for the type V1StandaloneSetup");
  }
}
