/**
 * generated by Xtext 2.19.0
 */
package org.xtext.mdl.mdl.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.mdl.mdl.CondFin;
import org.xtext.mdl.mdl.Contenu;
import org.xtext.mdl.mdl.Depot;
import org.xtext.mdl.mdl.Mail;
import org.xtext.mdl.mdl.MdlFactory;
import org.xtext.mdl.mdl.MdlPackage;
import org.xtext.mdl.mdl.QCM;
import org.xtext.mdl.mdl.Reminder;
import org.xtext.mdl.mdl.Step;
import org.xtext.mdl.mdl.SynchDate;
import org.xtext.mdl.mdl.TypeQCM;
import org.xtext.mdl.mdl.Workflow;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class MdlFactoryImpl extends EFactoryImpl implements MdlFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static MdlFactory init()
  {
    try
    {
      MdlFactory theMdlFactory = (MdlFactory)EPackage.Registry.INSTANCE.getEFactory(MdlPackage.eNS_URI);
      if (theMdlFactory != null)
      {
        return theMdlFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new MdlFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MdlFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case MdlPackage.WORKFLOW: return createWorkflow();
      case MdlPackage.STEP: return createStep();
      case MdlPackage.OBJECT: return createObject();
      case MdlPackage.COND_FIN: return createCondFin();
      case MdlPackage.SYNCH_DATE: return createSynchDate();
      case MdlPackage.DEPOT: return createDepot();
      case MdlPackage.QCM: return createQCM();
      case MdlPackage.TYPE_QCM: return createTypeQCM();
      case MdlPackage.REMINDER: return createReminder();
      case MdlPackage.MAIL: return createMail();
      case MdlPackage.CONTENU: return createContenu();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Workflow createWorkflow()
  {
    WorkflowImpl workflow = new WorkflowImpl();
    return workflow;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Step createStep()
  {
    StepImpl step = new StepImpl();
    return step;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public org.xtext.mdl.mdl.Object createObject()
  {
    ObjectImpl object = new ObjectImpl();
    return object;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CondFin createCondFin()
  {
    CondFinImpl condFin = new CondFinImpl();
    return condFin;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SynchDate createSynchDate()
  {
    SynchDateImpl synchDate = new SynchDateImpl();
    return synchDate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Depot createDepot()
  {
    DepotImpl depot = new DepotImpl();
    return depot;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public QCM createQCM()
  {
    QCMImpl qcm = new QCMImpl();
    return qcm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TypeQCM createTypeQCM()
  {
    TypeQCMImpl typeQCM = new TypeQCMImpl();
    return typeQCM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Reminder createReminder()
  {
    ReminderImpl reminder = new ReminderImpl();
    return reminder;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Mail createMail()
  {
    MailImpl mail = new MailImpl();
    return mail;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Contenu createContenu()
  {
    ContenuImpl contenu = new ContenuImpl();
    return contenu;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MdlPackage getMdlPackage()
  {
    return (MdlPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static MdlPackage getPackage()
  {
    return MdlPackage.eINSTANCE;
  }

} //MdlFactoryImpl
