/**
 * generated by Xtext 2.19.0
 */
package org.xtext.mdl.mdl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import org.xtext.mdl.mdl.MdlPackage;
import org.xtext.mdl.mdl.QCM;
import org.xtext.mdl.mdl.TypeQCM;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>QCM</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mdl.mdl.impl.QCMImpl#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.mdl.mdl.impl.QCMImpl#getIntitule <em>Intitule</em>}</li>
 *   <li>{@link org.xtext.mdl.mdl.impl.QCMImpl#getResponses <em>Responses</em>}</li>
 *   <li>{@link org.xtext.mdl.mdl.impl.QCMImpl#getSuite <em>Suite</em>}</li>
 * </ul>
 *
 * @generated
 */
public class QCMImpl extends MinimalEObjectImpl.Container implements QCM
{
  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected TypeQCM type;

  /**
   * The default value of the '{@link #getIntitule() <em>Intitule</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIntitule()
   * @generated
   * @ordered
   */
  protected static final String INTITULE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getIntitule() <em>Intitule</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIntitule()
   * @generated
   * @ordered
   */
  protected String intitule = INTITULE_EDEFAULT;

  /**
   * The cached value of the '{@link #getResponses() <em>Responses</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getResponses()
   * @generated
   * @ordered
   */
  protected EList<String> responses;

  /**
   * The cached value of the '{@link #getSuite() <em>Suite</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSuite()
   * @generated
   * @ordered
   */
  protected QCM suite;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected QCMImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MdlPackage.Literals.QCM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TypeQCM getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetType(TypeQCM newType, NotificationChain msgs)
  {
    TypeQCM oldType = type;
    type = newType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MdlPackage.QCM__TYPE, oldType, newType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(TypeQCM newType)
  {
    if (newType != type)
    {
      NotificationChain msgs = null;
      if (type != null)
        msgs = ((InternalEObject)type).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MdlPackage.QCM__TYPE, null, msgs);
      if (newType != null)
        msgs = ((InternalEObject)newType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MdlPackage.QCM__TYPE, null, msgs);
      msgs = basicSetType(newType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MdlPackage.QCM__TYPE, newType, newType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getIntitule()
  {
    return intitule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIntitule(String newIntitule)
  {
    String oldIntitule = intitule;
    intitule = newIntitule;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MdlPackage.QCM__INTITULE, oldIntitule, intitule));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getResponses()
  {
    if (responses == null)
    {
      responses = new EDataTypeEList<String>(String.class, this, MdlPackage.QCM__RESPONSES);
    }
    return responses;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public QCM getSuite()
  {
    return suite;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSuite(QCM newSuite, NotificationChain msgs)
  {
    QCM oldSuite = suite;
    suite = newSuite;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MdlPackage.QCM__SUITE, oldSuite, newSuite);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSuite(QCM newSuite)
  {
    if (newSuite != suite)
    {
      NotificationChain msgs = null;
      if (suite != null)
        msgs = ((InternalEObject)suite).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MdlPackage.QCM__SUITE, null, msgs);
      if (newSuite != null)
        msgs = ((InternalEObject)newSuite).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MdlPackage.QCM__SUITE, null, msgs);
      msgs = basicSetSuite(newSuite, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MdlPackage.QCM__SUITE, newSuite, newSuite));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MdlPackage.QCM__TYPE:
        return basicSetType(null, msgs);
      case MdlPackage.QCM__SUITE:
        return basicSetSuite(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MdlPackage.QCM__TYPE:
        return getType();
      case MdlPackage.QCM__INTITULE:
        return getIntitule();
      case MdlPackage.QCM__RESPONSES:
        return getResponses();
      case MdlPackage.QCM__SUITE:
        return getSuite();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MdlPackage.QCM__TYPE:
        setType((TypeQCM)newValue);
        return;
      case MdlPackage.QCM__INTITULE:
        setIntitule((String)newValue);
        return;
      case MdlPackage.QCM__RESPONSES:
        getResponses().clear();
        getResponses().addAll((Collection<? extends String>)newValue);
        return;
      case MdlPackage.QCM__SUITE:
        setSuite((QCM)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MdlPackage.QCM__TYPE:
        setType((TypeQCM)null);
        return;
      case MdlPackage.QCM__INTITULE:
        setIntitule(INTITULE_EDEFAULT);
        return;
      case MdlPackage.QCM__RESPONSES:
        getResponses().clear();
        return;
      case MdlPackage.QCM__SUITE:
        setSuite((QCM)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MdlPackage.QCM__TYPE:
        return type != null;
      case MdlPackage.QCM__INTITULE:
        return INTITULE_EDEFAULT == null ? intitule != null : !INTITULE_EDEFAULT.equals(intitule);
      case MdlPackage.QCM__RESPONSES:
        return responses != null && !responses.isEmpty();
      case MdlPackage.QCM__SUITE:
        return suite != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (intitule: ");
    result.append(intitule);
    result.append(", responses: ");
    result.append(responses);
    result.append(')');
    return result.toString();
  }

} //QCMImpl
