/*
 * generated by Xtext 2.20.0
 */
package org.xtext.mdl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.mdl.V1RuntimeModule;
import org.xtext.mdl.V1StandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class V1IdeSetup extends V1StandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new V1RuntimeModule(), new V1IdeModule()));
	}
	
}
