/**
 * generated by Xtext 2.19.0
 */
package org.xtext.mdl.ui.contentassist;

import org.xtext.mdl.ui.contentassist.AbstractV1ProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class V1ProposalProvider extends AbstractV1ProposalProvider {
}
