/**
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.v1.ui.contentassist;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class V1ProposalProvider /* implements AbstractV1ProposalProvider  */{
}
