/**
 * generated by Xtext 2.19.0
 */
package org.xtext.mdl;

import org.xtext.mdl.MdlStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MdlStandaloneSetup extends MdlStandaloneSetupGenerated {
  public static void doSetup() {
    new MdlStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
