/**
 * generated by Xtext 2.19.0
 */
package org.xtext.mdl;

import org.xtext.mdl.V1StandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class V1StandaloneSetup extends V1StandaloneSetupGenerated {
  public static void doSetup() {
    new V1StandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
