/**
 * generated by Xtext 2.19.0
 */
package org.xtext.mdl.v1;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rappel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mdl.v1.Rappel#getDate <em>Date</em>}</li>
 *   <li>{@link org.xtext.mdl.v1.Rappel#getMail <em>Mail</em>}</li>
 * </ul>
 *
 * @see org.xtext.mdl.v1.V1Package#getRappel()
 * @model
 * @generated
 */
public interface Rappel extends EObject
{
  /**
   * Returns the value of the '<em><b>Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Date</em>' attribute.
   * @see #setDate(String)
   * @see org.xtext.mdl.v1.V1Package#getRappel_Date()
   * @model
   * @generated
   */
  String getDate();

  /**
   * Sets the value of the '{@link org.xtext.mdl.v1.Rappel#getDate <em>Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Date</em>' attribute.
   * @see #getDate()
   * @generated
   */
  void setDate(String value);

  /**
   * Returns the value of the '<em><b>Mail</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mail</em>' containment reference.
   * @see #setMail(Mail)
   * @see org.xtext.mdl.v1.V1Package#getRappel_Mail()
   * @model containment="true"
   * @generated
   */
  Mail getMail();

  /**
   * Sets the value of the '{@link org.xtext.mdl.v1.Rappel#getMail <em>Mail</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mail</em>' containment reference.
   * @see #getMail()
   * @generated
   */
  void setMail(Mail value);

} // Rappel
