/**
 * generated by Xtext 2.19.0
 */
package org.xtext.mdl.v1;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type QCM</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mdl.v1.TypeQCM#getOPENQUESTION <em>OPENQUESTION</em>}</li>
 *   <li>{@link org.xtext.mdl.v1.TypeQCM#getCHECKBOX <em>CHECKBOX</em>}</li>
 *   <li>{@link org.xtext.mdl.v1.TypeQCM#getRADIOBUTTON <em>RADIOBUTTON</em>}</li>
 * </ul>
 *
 * @see org.xtext.mdl.v1.V1Package#getTypeQCM()
 * @model
 * @generated
 */
public interface TypeQCM extends EObject
{
  /**
   * Returns the value of the '<em><b>OPENQUESTION</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>OPENQUESTION</em>' attribute.
   * @see #setOPENQUESTION(String)
   * @see org.xtext.mdl.v1.V1Package#getTypeQCM_OPENQUESTION()
   * @model
   * @generated
   */
  String getOPENQUESTION();

  /**
   * Sets the value of the '{@link org.xtext.mdl.v1.TypeQCM#getOPENQUESTION <em>OPENQUESTION</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>OPENQUESTION</em>' attribute.
   * @see #getOPENQUESTION()
   * @generated
   */
  void setOPENQUESTION(String value);

  /**
   * Returns the value of the '<em><b>CHECKBOX</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>CHECKBOX</em>' attribute.
   * @see #setCHECKBOX(String)
   * @see org.xtext.mdl.v1.V1Package#getTypeQCM_CHECKBOX()
   * @model
   * @generated
   */
  String getCHECKBOX();

  /**
   * Sets the value of the '{@link org.xtext.mdl.v1.TypeQCM#getCHECKBOX <em>CHECKBOX</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>CHECKBOX</em>' attribute.
   * @see #getCHECKBOX()
   * @generated
   */
  void setCHECKBOX(String value);

  /**
   * Returns the value of the '<em><b>RADIOBUTTON</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>RADIOBUTTON</em>' attribute.
   * @see #setRADIOBUTTON(String)
   * @see org.xtext.mdl.v1.V1Package#getTypeQCM_RADIOBUTTON()
   * @model
   * @generated
   */
  String getRADIOBUTTON();

  /**
   * Sets the value of the '{@link org.xtext.mdl.v1.TypeQCM#getRADIOBUTTON <em>RADIOBUTTON</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>RADIOBUTTON</em>' attribute.
   * @see #getRADIOBUTTON()
   * @generated
   */
  void setRADIOBUTTON(String value);

} // TypeQCM
