/**
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.v1.ide;

import com.google.inject.Injector;
import org.xtext.dsl.v1.V1StandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class V1IdeSetup extends V1StandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from V1RuntimeModule to Module"
      + "\nType mismatch: cannot convert from V1IdeModule to Module");
  }
}
