/**
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.v1.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class V1IdeModule /* implements AbstractV1IdeModule  */{
}
