/**
 * generated by Xtext 2.19.0
 */
package org.xtext.mdl.v1;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.mdl.v1.V1Factory
 * @model kind="package"
 * @generated
 */
public interface V1Package extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "v1";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/mdl/V1";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "v1";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  V1Package eINSTANCE = org.xtext.mdl.v1.impl.V1PackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.mdl.v1.impl.WorkflowImpl <em>Workflow</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mdl.v1.impl.WorkflowImpl
   * @see org.xtext.mdl.v1.impl.V1PackageImpl#getWorkflow()
   * @generated
   */
  int WORKFLOW = 0;

  /**
   * The feature id for the '<em><b>Date Debut</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORKFLOW__DATE_DEBUT = 0;

  /**
   * The feature id for the '<em><b>Etapes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORKFLOW__ETAPES = 1;

  /**
   * The number of structural features of the '<em>Workflow</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORKFLOW_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.mdl.v1.impl.EtapeImpl <em>Etape</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mdl.v1.impl.EtapeImpl
   * @see org.xtext.mdl.v1.impl.V1PackageImpl#getEtape()
   * @generated
   */
  int ETAPE = 1;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ETAPE__ID = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ETAPE__NAME = 1;

  /**
   * The feature id for the '<em><b>Rappels</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ETAPE__RAPPELS = 2;

  /**
   * The feature id for the '<em><b>Obj</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ETAPE__OBJ = 3;

  /**
   * The number of structural features of the '<em>Etape</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ETAPE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.mdl.v1.impl.ObjetImpl <em>Objet</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mdl.v1.impl.ObjetImpl
   * @see org.xtext.mdl.v1.impl.V1PackageImpl#getObjet()
   * @generated
   */
  int OBJET = 2;

  /**
   * The feature id for the '<em><b>Obj</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__OBJ = 0;

  /**
   * The feature id for the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__COND = 1;

  /**
   * The feature id for the '<em><b>Mail</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__MAIL = 2;

  /**
   * The feature id for the '<em><b>Date Envoi</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__DATE_ENVOI = 3;

  /**
   * The feature id for the '<em><b>Synch Date</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__SYNCH_DATE = 4;

  /**
   * The feature id for the '<em><b>Date Fin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__DATE_FIN = 5;

  /**
   * The feature id for the '<em><b>Depot</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__DEPOT = 6;

  /**
   * The number of structural features of the '<em>Objet</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link org.xtext.mdl.v1.impl.CondFinImpl <em>Cond Fin</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mdl.v1.impl.CondFinImpl
   * @see org.xtext.mdl.v1.impl.V1PackageImpl#getCondFin()
   * @generated
   */
  int COND_FIN = 3;

  /**
   * The feature id for the '<em><b>Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COND_FIN__DATE = 0;

  /**
   * The number of structural features of the '<em>Cond Fin</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COND_FIN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.mdl.v1.impl.SynchDateImpl <em>Synch Date</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mdl.v1.impl.SynchDateImpl
   * @see org.xtext.mdl.v1.impl.V1PackageImpl#getSynchDate()
   * @generated
   */
  int SYNCH_DATE = 4;

  /**
   * The feature id for the '<em><b>Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYNCH_DATE__START = 0;

  /**
   * The feature id for the '<em><b>End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYNCH_DATE__END = 1;

  /**
   * The feature id for the '<em><b>Precision</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYNCH_DATE__PRECISION = 2;

  /**
   * The number of structural features of the '<em>Synch Date</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYNCH_DATE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.mdl.v1.impl.DepotImpl <em>Depot</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mdl.v1.impl.DepotImpl
   * @see org.xtext.mdl.v1.impl.V1PackageImpl#getDepot()
   * @generated
   */
  int DEPOT = 5;

  /**
   * The feature id for the '<em><b>Intitule</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPOT__INTITULE = 0;

  /**
   * The feature id for the '<em><b>Limite Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPOT__LIMITE_SIZE = 1;

  /**
   * The feature id for the '<em><b>Format</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPOT__FORMAT = 2;

  /**
   * The number of structural features of the '<em>Depot</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPOT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.mdl.v1.impl.QCMImpl <em>QCM</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mdl.v1.impl.QCMImpl
   * @see org.xtext.mdl.v1.impl.V1PackageImpl#getQCM()
   * @generated
   */
  int QCM = 6;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QCM__TYPE = 0;

  /**
   * The feature id for the '<em><b>Intitule</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QCM__INTITULE = 1;

  /**
   * The feature id for the '<em><b>Responses</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QCM__RESPONSES = 2;

  /**
   * The feature id for the '<em><b>Suite</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QCM__SUITE = 3;

  /**
   * The number of structural features of the '<em>QCM</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QCM_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.mdl.v1.impl.TypeQCMImpl <em>Type QCM</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mdl.v1.impl.TypeQCMImpl
   * @see org.xtext.mdl.v1.impl.V1PackageImpl#getTypeQCM()
   * @generated
   */
  int TYPE_QCM = 7;

  /**
   * The feature id for the '<em><b>OPENQUESTION</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_QCM__OPENQUESTION = 0;

  /**
   * The feature id for the '<em><b>CHECKBOX</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_QCM__CHECKBOX = 1;

  /**
   * The feature id for the '<em><b>RADIOBUTTON</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_QCM__RADIOBUTTON = 2;

  /**
   * The number of structural features of the '<em>Type QCM</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_QCM_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.mdl.v1.impl.RappelImpl <em>Rappel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mdl.v1.impl.RappelImpl
   * @see org.xtext.mdl.v1.impl.V1PackageImpl#getRappel()
   * @generated
   */
  int RAPPEL = 8;

  /**
   * The feature id for the '<em><b>Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RAPPEL__DATE = 0;

  /**
   * The feature id for the '<em><b>Mail</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RAPPEL__MAIL = 1;

  /**
   * The number of structural features of the '<em>Rappel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RAPPEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.mdl.v1.impl.MailImpl <em>Mail</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mdl.v1.impl.MailImpl
   * @see org.xtext.mdl.v1.impl.V1PackageImpl#getMail()
   * @generated
   */
  int MAIL = 9;

  /**
   * The feature id for the '<em><b>Expediteur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIL__EXPEDITEUR = 0;

  /**
   * The feature id for the '<em><b>Destinataire</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIL__DESTINATAIRE = 1;

  /**
   * The feature id for the '<em><b>Pj</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIL__PJ = 2;

  /**
   * The feature id for the '<em><b>Corps</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIL__CORPS = 3;

  /**
   * The number of structural features of the '<em>Mail</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIL_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.mdl.v1.impl.ContenuImpl <em>Contenu</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mdl.v1.impl.ContenuImpl
   * @see org.xtext.mdl.v1.impl.V1PackageImpl#getContenu()
   * @generated
   */
  int CONTENU = 10;

  /**
   * The feature id for the '<em><b>Corps</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENU__CORPS = 0;

  /**
   * The feature id for the '<em><b>Invitation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENU__INVITATION = 1;

  /**
   * The number of structural features of the '<em>Contenu</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENU_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.mdl.v1.Workflow <em>Workflow</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Workflow</em>'.
   * @see org.xtext.mdl.v1.Workflow
   * @generated
   */
  EClass getWorkflow();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdl.v1.Workflow#getDateDebut <em>Date Debut</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Date Debut</em>'.
   * @see org.xtext.mdl.v1.Workflow#getDateDebut()
   * @see #getWorkflow()
   * @generated
   */
  EAttribute getWorkflow_DateDebut();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.mdl.v1.Workflow#getEtapes <em>Etapes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Etapes</em>'.
   * @see org.xtext.mdl.v1.Workflow#getEtapes()
   * @see #getWorkflow()
   * @generated
   */
  EReference getWorkflow_Etapes();

  /**
   * Returns the meta object for class '{@link org.xtext.mdl.v1.Etape <em>Etape</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Etape</em>'.
   * @see org.xtext.mdl.v1.Etape
   * @generated
   */
  EClass getEtape();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdl.v1.Etape#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.mdl.v1.Etape#getId()
   * @see #getEtape()
   * @generated
   */
  EAttribute getEtape_Id();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdl.v1.Etape#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.mdl.v1.Etape#getName()
   * @see #getEtape()
   * @generated
   */
  EAttribute getEtape_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.mdl.v1.Etape#getRappels <em>Rappels</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rappels</em>'.
   * @see org.xtext.mdl.v1.Etape#getRappels()
   * @see #getEtape()
   * @generated
   */
  EReference getEtape_Rappels();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mdl.v1.Etape#getObj <em>Obj</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Obj</em>'.
   * @see org.xtext.mdl.v1.Etape#getObj()
   * @see #getEtape()
   * @generated
   */
  EReference getEtape_Obj();

  /**
   * Returns the meta object for class '{@link org.xtext.mdl.v1.Objet <em>Objet</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Objet</em>'.
   * @see org.xtext.mdl.v1.Objet
   * @generated
   */
  EClass getObjet();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mdl.v1.Objet#getObj <em>Obj</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Obj</em>'.
   * @see org.xtext.mdl.v1.Objet#getObj()
   * @see #getObjet()
   * @generated
   */
  EReference getObjet_Obj();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mdl.v1.Objet#getCond <em>Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cond</em>'.
   * @see org.xtext.mdl.v1.Objet#getCond()
   * @see #getObjet()
   * @generated
   */
  EReference getObjet_Cond();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mdl.v1.Objet#getMail <em>Mail</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Mail</em>'.
   * @see org.xtext.mdl.v1.Objet#getMail()
   * @see #getObjet()
   * @generated
   */
  EReference getObjet_Mail();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdl.v1.Objet#getDateEnvoi <em>Date Envoi</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Date Envoi</em>'.
   * @see org.xtext.mdl.v1.Objet#getDateEnvoi()
   * @see #getObjet()
   * @generated
   */
  EAttribute getObjet_DateEnvoi();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mdl.v1.Objet#getSynchDate <em>Synch Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Synch Date</em>'.
   * @see org.xtext.mdl.v1.Objet#getSynchDate()
   * @see #getObjet()
   * @generated
   */
  EReference getObjet_SynchDate();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdl.v1.Objet#getDateFin <em>Date Fin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Date Fin</em>'.
   * @see org.xtext.mdl.v1.Objet#getDateFin()
   * @see #getObjet()
   * @generated
   */
  EAttribute getObjet_DateFin();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mdl.v1.Objet#getDepot <em>Depot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Depot</em>'.
   * @see org.xtext.mdl.v1.Objet#getDepot()
   * @see #getObjet()
   * @generated
   */
  EReference getObjet_Depot();

  /**
   * Returns the meta object for class '{@link org.xtext.mdl.v1.CondFin <em>Cond Fin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cond Fin</em>'.
   * @see org.xtext.mdl.v1.CondFin
   * @generated
   */
  EClass getCondFin();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdl.v1.CondFin#getDate <em>Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Date</em>'.
   * @see org.xtext.mdl.v1.CondFin#getDate()
   * @see #getCondFin()
   * @generated
   */
  EAttribute getCondFin_Date();

  /**
   * Returns the meta object for class '{@link org.xtext.mdl.v1.SynchDate <em>Synch Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Synch Date</em>'.
   * @see org.xtext.mdl.v1.SynchDate
   * @generated
   */
  EClass getSynchDate();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdl.v1.SynchDate#getStart <em>Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start</em>'.
   * @see org.xtext.mdl.v1.SynchDate#getStart()
   * @see #getSynchDate()
   * @generated
   */
  EAttribute getSynchDate_Start();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdl.v1.SynchDate#getEnd <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End</em>'.
   * @see org.xtext.mdl.v1.SynchDate#getEnd()
   * @see #getSynchDate()
   * @generated
   */
  EAttribute getSynchDate_End();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdl.v1.SynchDate#getPrecision <em>Precision</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Precision</em>'.
   * @see org.xtext.mdl.v1.SynchDate#getPrecision()
   * @see #getSynchDate()
   * @generated
   */
  EAttribute getSynchDate_Precision();

  /**
   * Returns the meta object for class '{@link org.xtext.mdl.v1.Depot <em>Depot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Depot</em>'.
   * @see org.xtext.mdl.v1.Depot
   * @generated
   */
  EClass getDepot();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdl.v1.Depot#getIntitule <em>Intitule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Intitule</em>'.
   * @see org.xtext.mdl.v1.Depot#getIntitule()
   * @see #getDepot()
   * @generated
   */
  EAttribute getDepot_Intitule();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdl.v1.Depot#getLimiteSize <em>Limite Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Limite Size</em>'.
   * @see org.xtext.mdl.v1.Depot#getLimiteSize()
   * @see #getDepot()
   * @generated
   */
  EAttribute getDepot_LimiteSize();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.mdl.v1.Depot#getFormat <em>Format</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Format</em>'.
   * @see org.xtext.mdl.v1.Depot#getFormat()
   * @see #getDepot()
   * @generated
   */
  EAttribute getDepot_Format();

  /**
   * Returns the meta object for class '{@link org.xtext.mdl.v1.QCM <em>QCM</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>QCM</em>'.
   * @see org.xtext.mdl.v1.QCM
   * @generated
   */
  EClass getQCM();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mdl.v1.QCM#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.xtext.mdl.v1.QCM#getType()
   * @see #getQCM()
   * @generated
   */
  EReference getQCM_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdl.v1.QCM#getIntitule <em>Intitule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Intitule</em>'.
   * @see org.xtext.mdl.v1.QCM#getIntitule()
   * @see #getQCM()
   * @generated
   */
  EAttribute getQCM_Intitule();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.mdl.v1.QCM#getResponses <em>Responses</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Responses</em>'.
   * @see org.xtext.mdl.v1.QCM#getResponses()
   * @see #getQCM()
   * @generated
   */
  EAttribute getQCM_Responses();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mdl.v1.QCM#getSuite <em>Suite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Suite</em>'.
   * @see org.xtext.mdl.v1.QCM#getSuite()
   * @see #getQCM()
   * @generated
   */
  EReference getQCM_Suite();

  /**
   * Returns the meta object for class '{@link org.xtext.mdl.v1.TypeQCM <em>Type QCM</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type QCM</em>'.
   * @see org.xtext.mdl.v1.TypeQCM
   * @generated
   */
  EClass getTypeQCM();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdl.v1.TypeQCM#getOPENQUESTION <em>OPENQUESTION</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>OPENQUESTION</em>'.
   * @see org.xtext.mdl.v1.TypeQCM#getOPENQUESTION()
   * @see #getTypeQCM()
   * @generated
   */
  EAttribute getTypeQCM_OPENQUESTION();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdl.v1.TypeQCM#getCHECKBOX <em>CHECKBOX</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>CHECKBOX</em>'.
   * @see org.xtext.mdl.v1.TypeQCM#getCHECKBOX()
   * @see #getTypeQCM()
   * @generated
   */
  EAttribute getTypeQCM_CHECKBOX();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdl.v1.TypeQCM#getRADIOBUTTON <em>RADIOBUTTON</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>RADIOBUTTON</em>'.
   * @see org.xtext.mdl.v1.TypeQCM#getRADIOBUTTON()
   * @see #getTypeQCM()
   * @generated
   */
  EAttribute getTypeQCM_RADIOBUTTON();

  /**
   * Returns the meta object for class '{@link org.xtext.mdl.v1.Rappel <em>Rappel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rappel</em>'.
   * @see org.xtext.mdl.v1.Rappel
   * @generated
   */
  EClass getRappel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdl.v1.Rappel#getDate <em>Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Date</em>'.
   * @see org.xtext.mdl.v1.Rappel#getDate()
   * @see #getRappel()
   * @generated
   */
  EAttribute getRappel_Date();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mdl.v1.Rappel#getMail <em>Mail</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Mail</em>'.
   * @see org.xtext.mdl.v1.Rappel#getMail()
   * @see #getRappel()
   * @generated
   */
  EReference getRappel_Mail();

  /**
   * Returns the meta object for class '{@link org.xtext.mdl.v1.Mail <em>Mail</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mail</em>'.
   * @see org.xtext.mdl.v1.Mail
   * @generated
   */
  EClass getMail();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdl.v1.Mail#getExpediteur <em>Expediteur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Expediteur</em>'.
   * @see org.xtext.mdl.v1.Mail#getExpediteur()
   * @see #getMail()
   * @generated
   */
  EAttribute getMail_Expediteur();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.mdl.v1.Mail#getDestinataire <em>Destinataire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Destinataire</em>'.
   * @see org.xtext.mdl.v1.Mail#getDestinataire()
   * @see #getMail()
   * @generated
   */
  EAttribute getMail_Destinataire();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdl.v1.Mail#getPj <em>Pj</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pj</em>'.
   * @see org.xtext.mdl.v1.Mail#getPj()
   * @see #getMail()
   * @generated
   */
  EAttribute getMail_Pj();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mdl.v1.Mail#getCorps <em>Corps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Corps</em>'.
   * @see org.xtext.mdl.v1.Mail#getCorps()
   * @see #getMail()
   * @generated
   */
  EReference getMail_Corps();

  /**
   * Returns the meta object for class '{@link org.xtext.mdl.v1.Contenu <em>Contenu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Contenu</em>'.
   * @see org.xtext.mdl.v1.Contenu
   * @generated
   */
  EClass getContenu();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdl.v1.Contenu#getCorps <em>Corps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Corps</em>'.
   * @see org.xtext.mdl.v1.Contenu#getCorps()
   * @see #getContenu()
   * @generated
   */
  EAttribute getContenu_Corps();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mdl.v1.Contenu#getInvitation <em>Invitation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Invitation</em>'.
   * @see org.xtext.mdl.v1.Contenu#getInvitation()
   * @see #getContenu()
   * @generated
   */
  EAttribute getContenu_Invitation();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  V1Factory getV1Factory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.mdl.v1.impl.WorkflowImpl <em>Workflow</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mdl.v1.impl.WorkflowImpl
     * @see org.xtext.mdl.v1.impl.V1PackageImpl#getWorkflow()
     * @generated
     */
    EClass WORKFLOW = eINSTANCE.getWorkflow();

    /**
     * The meta object literal for the '<em><b>Date Debut</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORKFLOW__DATE_DEBUT = eINSTANCE.getWorkflow_DateDebut();

    /**
     * The meta object literal for the '<em><b>Etapes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORKFLOW__ETAPES = eINSTANCE.getWorkflow_Etapes();

    /**
     * The meta object literal for the '{@link org.xtext.mdl.v1.impl.EtapeImpl <em>Etape</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mdl.v1.impl.EtapeImpl
     * @see org.xtext.mdl.v1.impl.V1PackageImpl#getEtape()
     * @generated
     */
    EClass ETAPE = eINSTANCE.getEtape();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ETAPE__ID = eINSTANCE.getEtape_Id();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ETAPE__NAME = eINSTANCE.getEtape_Name();

    /**
     * The meta object literal for the '<em><b>Rappels</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ETAPE__RAPPELS = eINSTANCE.getEtape_Rappels();

    /**
     * The meta object literal for the '<em><b>Obj</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ETAPE__OBJ = eINSTANCE.getEtape_Obj();

    /**
     * The meta object literal for the '{@link org.xtext.mdl.v1.impl.ObjetImpl <em>Objet</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mdl.v1.impl.ObjetImpl
     * @see org.xtext.mdl.v1.impl.V1PackageImpl#getObjet()
     * @generated
     */
    EClass OBJET = eINSTANCE.getObjet();

    /**
     * The meta object literal for the '<em><b>Obj</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJET__OBJ = eINSTANCE.getObjet_Obj();

    /**
     * The meta object literal for the '<em><b>Cond</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJET__COND = eINSTANCE.getObjet_Cond();

    /**
     * The meta object literal for the '<em><b>Mail</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJET__MAIL = eINSTANCE.getObjet_Mail();

    /**
     * The meta object literal for the '<em><b>Date Envoi</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJET__DATE_ENVOI = eINSTANCE.getObjet_DateEnvoi();

    /**
     * The meta object literal for the '<em><b>Synch Date</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJET__SYNCH_DATE = eINSTANCE.getObjet_SynchDate();

    /**
     * The meta object literal for the '<em><b>Date Fin</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJET__DATE_FIN = eINSTANCE.getObjet_DateFin();

    /**
     * The meta object literal for the '<em><b>Depot</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJET__DEPOT = eINSTANCE.getObjet_Depot();

    /**
     * The meta object literal for the '{@link org.xtext.mdl.v1.impl.CondFinImpl <em>Cond Fin</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mdl.v1.impl.CondFinImpl
     * @see org.xtext.mdl.v1.impl.V1PackageImpl#getCondFin()
     * @generated
     */
    EClass COND_FIN = eINSTANCE.getCondFin();

    /**
     * The meta object literal for the '<em><b>Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COND_FIN__DATE = eINSTANCE.getCondFin_Date();

    /**
     * The meta object literal for the '{@link org.xtext.mdl.v1.impl.SynchDateImpl <em>Synch Date</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mdl.v1.impl.SynchDateImpl
     * @see org.xtext.mdl.v1.impl.V1PackageImpl#getSynchDate()
     * @generated
     */
    EClass SYNCH_DATE = eINSTANCE.getSynchDate();

    /**
     * The meta object literal for the '<em><b>Start</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYNCH_DATE__START = eINSTANCE.getSynchDate_Start();

    /**
     * The meta object literal for the '<em><b>End</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYNCH_DATE__END = eINSTANCE.getSynchDate_End();

    /**
     * The meta object literal for the '<em><b>Precision</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYNCH_DATE__PRECISION = eINSTANCE.getSynchDate_Precision();

    /**
     * The meta object literal for the '{@link org.xtext.mdl.v1.impl.DepotImpl <em>Depot</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mdl.v1.impl.DepotImpl
     * @see org.xtext.mdl.v1.impl.V1PackageImpl#getDepot()
     * @generated
     */
    EClass DEPOT = eINSTANCE.getDepot();

    /**
     * The meta object literal for the '<em><b>Intitule</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEPOT__INTITULE = eINSTANCE.getDepot_Intitule();

    /**
     * The meta object literal for the '<em><b>Limite Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEPOT__LIMITE_SIZE = eINSTANCE.getDepot_LimiteSize();

    /**
     * The meta object literal for the '<em><b>Format</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEPOT__FORMAT = eINSTANCE.getDepot_Format();

    /**
     * The meta object literal for the '{@link org.xtext.mdl.v1.impl.QCMImpl <em>QCM</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mdl.v1.impl.QCMImpl
     * @see org.xtext.mdl.v1.impl.V1PackageImpl#getQCM()
     * @generated
     */
    EClass QCM = eINSTANCE.getQCM();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QCM__TYPE = eINSTANCE.getQCM_Type();

    /**
     * The meta object literal for the '<em><b>Intitule</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QCM__INTITULE = eINSTANCE.getQCM_Intitule();

    /**
     * The meta object literal for the '<em><b>Responses</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QCM__RESPONSES = eINSTANCE.getQCM_Responses();

    /**
     * The meta object literal for the '<em><b>Suite</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QCM__SUITE = eINSTANCE.getQCM_Suite();

    /**
     * The meta object literal for the '{@link org.xtext.mdl.v1.impl.TypeQCMImpl <em>Type QCM</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mdl.v1.impl.TypeQCMImpl
     * @see org.xtext.mdl.v1.impl.V1PackageImpl#getTypeQCM()
     * @generated
     */
    EClass TYPE_QCM = eINSTANCE.getTypeQCM();

    /**
     * The meta object literal for the '<em><b>OPENQUESTION</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_QCM__OPENQUESTION = eINSTANCE.getTypeQCM_OPENQUESTION();

    /**
     * The meta object literal for the '<em><b>CHECKBOX</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_QCM__CHECKBOX = eINSTANCE.getTypeQCM_CHECKBOX();

    /**
     * The meta object literal for the '<em><b>RADIOBUTTON</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_QCM__RADIOBUTTON = eINSTANCE.getTypeQCM_RADIOBUTTON();

    /**
     * The meta object literal for the '{@link org.xtext.mdl.v1.impl.RappelImpl <em>Rappel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mdl.v1.impl.RappelImpl
     * @see org.xtext.mdl.v1.impl.V1PackageImpl#getRappel()
     * @generated
     */
    EClass RAPPEL = eINSTANCE.getRappel();

    /**
     * The meta object literal for the '<em><b>Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RAPPEL__DATE = eINSTANCE.getRappel_Date();

    /**
     * The meta object literal for the '<em><b>Mail</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RAPPEL__MAIL = eINSTANCE.getRappel_Mail();

    /**
     * The meta object literal for the '{@link org.xtext.mdl.v1.impl.MailImpl <em>Mail</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mdl.v1.impl.MailImpl
     * @see org.xtext.mdl.v1.impl.V1PackageImpl#getMail()
     * @generated
     */
    EClass MAIL = eINSTANCE.getMail();

    /**
     * The meta object literal for the '<em><b>Expediteur</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAIL__EXPEDITEUR = eINSTANCE.getMail_Expediteur();

    /**
     * The meta object literal for the '<em><b>Destinataire</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAIL__DESTINATAIRE = eINSTANCE.getMail_Destinataire();

    /**
     * The meta object literal for the '<em><b>Pj</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAIL__PJ = eINSTANCE.getMail_Pj();

    /**
     * The meta object literal for the '<em><b>Corps</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAIL__CORPS = eINSTANCE.getMail_Corps();

    /**
     * The meta object literal for the '{@link org.xtext.mdl.v1.impl.ContenuImpl <em>Contenu</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mdl.v1.impl.ContenuImpl
     * @see org.xtext.mdl.v1.impl.V1PackageImpl#getContenu()
     * @generated
     */
    EClass CONTENU = eINSTANCE.getContenu();

    /**
     * The meta object literal for the '<em><b>Corps</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTENU__CORPS = eINSTANCE.getContenu_Corps();

    /**
     * The meta object literal for the '<em><b>Invitation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTENU__INVITATION = eINSTANCE.getContenu_Invitation();

  }

} //V1Package
